SELECT
EMP_ID, EMP_NAME,EMP_NO, SALARY,JOB_NAME,NVL( DEPT_TITLE, '없음') 
FROM
EMPLOYEE
JOIN JOB USING (JOB_CODE)
LEFT JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
WHERE 
DECODE(SUBSTR(EMP_NO,8,1),1,'M',2,'F') = 'F' 
AND 
SALARY BETWEEN 4000000 AND 8000000
ORDER BY 
SALARY ASC;